config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/patients'

  get 'static_pages/doctors'

  get 'static_pages/microbiologists'

  get 'static_pages/accounting'

  devise_for :labs
  devise_for :secretaries
  resources :bills
  resources :illness_details
  resources :hospitalizations
  resources :visits
  resources :blood_chemistry_tests
  resources :blood_tests
  resources :microbiologists
  resources :nurses
  resources :doctors
  devise_for :admins
  resources :patients
  devise_for :users

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :doctor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :patient
  belongs_to :visit
  belongs_to :hospitalization
end

app/models/blood_chemistry_test.rb
class BloodChemistryTest < ActiveRecord::Base
  belongs_to :patient
  belongs_to :microbiologist
end

app/models/blood_test.rb
class BloodTest < ActiveRecord::Base
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :admin
end

app/models/hospitalization.rb
class Hospitalization < ActiveRecord::Base
  belongs_to :doctor
end

app/models/illness_detail.rb
class IllnessDetail < ActiveRecord::Base
  belongs_to :patient
  belongs_to :hospitalization
  belongs_to :visit
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :microbiologist
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/microbiologist.rb
class Microbiologist < ActiveRecord::Base
	belongs_to :lab
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/secretary.rb
class Secretary < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :patient
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:visitDate, :Hospitalized, :doctor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/blood_tests_helper.rb
module BloodTestsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/nurses_helper.rb
module NursesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-6 large-centered columns">
      <div class="field">
        <%= f.label :visitDate, 'Appointment Date' %><br>
          <%= f.date_select :visitDate, :order => [:day, :month, :year],:start_year => Time.now.year, :end_year => Time.now.year + 100 %>
      </div>
      <div class="field">
        <%= f.label :Hospitalized, 'Hospitalized' %>
        <%= f.check_box :Hospitalized %>
      </div>
      <div class="field">
        <%= f.label :doctor_id, 'Doctor'%><br>
        <%= f.collection_select :doctor_id, Doctor.all, :id, :email %>
      </div>
      <div class="twelve columns text-center"><br />
        <div class="actions">
          <%= link_to 'Back', visits_path, class:"button round info" %> <%= f.submit "Create Appointment", class:"button round success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/visits/edit.html.erb
<div class="twelve columns text-center"><br />
  <h1>Edit Appointment</h1>
</div>
<%= render 'form' %>

app/views/visits/index.html.erb
<%if user_signed_in? || admin_signed_in?%>

<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Appointment Database</h1>
  </div>

  <div class="small-10 small-centered columns">
    <table>
      <thead>
        <tr>
          <th>Appointment Date</th>
          <th>Hospitalized</th>
          <th>Doctor</th>
          <th>Operations</th>
        </tr>
      </thead>

      <tbody>
        <% @visits.each do |visit| %>
          <% if visit.doctor.email == current_admin.email %>
          <tr>
            <td><%= visit.visitDate %></td>
            <td>
              <% if visit.Hospitalized %>
                Yes
              <% else %>
                No
              <% end %>
            </td>
            <td><%= visit.doctor.name %> <%= visit.doctor.lastname %></td>
            <td><%= link_to 'Edit', edit_visit_path(visit), class: "button tiny round" %> <%= link_to 'Delete', visit, method: :delete, data: { confirm: 'Are you sure?' }, class: "button tiny round alert" %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<div class="row">
  <div class="twelve columns text-center"><br />
    <%= link_to 'New Appointment', new_visit_path, class: "button round info"  %>
  </div>
</div>
<% else %>
  You must me logged in as Doctor to view this page.
<% end %>

app/views/visits/new.html.erb
<div class="twelve columns text-center"><br />
  <h1>New Appointment</h1>
</div>
<%= render 'form' %>

app/views/visits/show.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Your Appointment Was Successfully Scheduled!</h1>
    <p> Please continue! </p>
    <%= link_to 'Continue', visits_path, class: "button success" %>
  </div>
</div>