config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/patients'

  get 'static_pages/doctors'

  get 'static_pages/microbiologists'

  get 'static_pages/accounting'

  devise_for :labs
  devise_for :secretaries
  resources :bills
  resources :illness_details
  resources :hospitalizations
  resources :visits
  resources :blood_chemistry_tests
  resources :blood_tests
  resources :microbiologists
  resources :nurses
  resources :doctors
  devise_for :admins
  resources :patients
  devise_for :users

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :doctor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :patient
  belongs_to :visit
  belongs_to :hospitalization
end

app/models/blood_test.rb
class BloodTest < ActiveRecord::Base
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :admin
end

app/models/hospitalization.rb
class Hospitalization < ActiveRecord::Base
  belongs_to :doctor
end

app/models/illness_detail.rb
class IllnessDetail < ActiveRecord::Base
  belongs_to :patient
  belongs_to :hospitalization
  belongs_to :visit
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :microbiologist
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/microbiologist.rb
class Microbiologist < ActiveRecord::Base
	belongs_to :lab
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/secretary.rb
class Secretary < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :patient
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/hospitalizations_controller.rb
class HospitalizationsController < ApplicationController
  before_action :set_hospitalization, only: [:show, :edit, :update, :destroy]

  # GET /hospitalizations
  # GET /hospitalizations.json
  def index
    @hospitalizations = Hospitalization.all
  end

  # GET /hospitalizations/1
  # GET /hospitalizations/1.json
  def show
  end

  # GET /hospitalizations/new
  def new
    @hospitalization = Hospitalization.new
  end

  # GET /hospitalizations/1/edit
  def edit
  end

  # POST /hospitalizations
  # POST /hospitalizations.json
  def create
    @hospitalization = Hospitalization.new(hospitalization_params)

    respond_to do |format|
      if @hospitalization.save
        format.html { redirect_to @hospitalization, notice: 'Hospitalization was successfully created.' }
        format.json { render :show, status: :created, location: @hospitalization }
      else
        format.html { render :new }
        format.json { render json: @hospitalization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitalizations/1
  # PATCH/PUT /hospitalizations/1.json
  def update
    respond_to do |format|
      if @hospitalization.update(hospitalization_params)
        format.html { redirect_to @hospitalization, notice: 'Hospitalization was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospitalization }
      else
        format.html { render :edit }
        format.json { render json: @hospitalization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitalizations/1
  # DELETE /hospitalizations/1.json
  def destroy
    @hospitalization.destroy
    respond_to do |format|
      format.html { redirect_to hospitalizations_url, notice: 'Hospitalization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospitalization
      @hospitalization = Hospitalization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospitalization_params
      params.require(:hospitalization).permit(:daysSpent, :roomNumber, :entryDate, :doctor_id, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/blood_tests_helper.rb
module BloodTestsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitalizations_helper.rb
module HospitalizationsHelper
end

app/helpers/nurses_helper.rb
module NursesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/hospitalizations/_form.html.erb
<%= form_for(@hospitalization) do |f| %>
  <% if @hospitalization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospitalization.errors.count, "error") %> prohibited this hospitalization from being saved:</h2>

      <ul>
      <% @hospitalization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="small-6 large-centered columns">
      <div class="field">
        <%= f.label :patient_id, "Patient" %><br>
        <%= f.collection_select :patient_id, Patient.all, :id, :email %>
      </div>
      <div class="field">
        <%= f.label :daysSpent, "Days Spent" %><br>
        <%= f.number_field :daysSpent %>
      </div>
      <div class="field">
        <%= f.label :roomNumber, "Room Number" %><br>
        <%= f.text_field :roomNumber %>
      </div>
      <div class="field">
        <%= f.label :entryDate, "Entry Date" %><br>
        <%= f.date_select :entryDate %>
      </div>
      <div class="field">
        <%= f.label :doctor_id, "Doctor" %><br>
        <%= f.collection_select :doctor_id, Doctor.all, :id, :email %>
      </div>
      <div class="field">
        <%= f.label :cost, "Cost" %><br>
        <%= f.text_field :cost %>
      </div>
      <div class="field">
        <%= f.label :payed, "Payed?" %><br>
        <%= f.check_box :payed %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns text-center"><br />
      <div class="actions">
        <%= link_to 'Back', hospitalizations_path, class:"button round secondary" %> <%= f.submit "Submit", class:"button round success"%>
      </div>
    </div>
  </div>
<% end %>

app/views/hospitalizations/edit.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Edit Hospitalization</h1>
  </div>
</div>
<%= render 'form' %>

app/views/hospitalizations/index.html.erb
<p id="notice"><%= notice %></p>
<%if admin_signed_in?%>

<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Hospitalization Database</h1>
  </div>

  <div class="small-10 small-centered columns">
    <table>
      <thead>
        <tr>
          <th>Days Spent</th>
          <th>Room Number</th>
          <th>Entry Date</th>
          <th>Doctor</th>
          <th>Cost</th>
          <th>Payed</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @hospitalizations.each do |hospitalization| %>
          <tr>
            <td><%= hospitalization.daysSpent %></td>
            <td><%= hospitalization.roomNumber %></td>
            <td><%= hospitalization.entryDate %></td>
            <td><%= hospitalization.doctor.name %><%= hospitalization.doctor.lastname %></td>
            <td><%= hospitalization.cost %></td>
            <td><%= hospitalization.payed %></td>
            <td><%= link_to 'Edit', edit_hospitalization_path(hospitalization), class:"button round tiny info" %></td>
            <td><%= link_to 'Delete', hospitalization, method: :delete, data: { confirm: 'Are you sure?' }, class:"button round tiny alert" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

</div>
<br>

<div class="row">
  <div class="twelve columns text-center"><br />
    <%= link_to 'New Hospitalization', new_hospitalization_path, class:"button round info" %>
  </div>
</div>
<%else%>
  You must be logged in as a Doctor to view this page.
<%end%>

app/views/hospitalizations/new.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>New Hospitalization</h1>
  </div>
</div>
<%= render 'form' %>

app/views/hospitalizations/show.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Your Hospitalization Was Successfully Scheduled!</h1>
    <p> Please continue! </p>
    <%= link_to 'Continue', hospitalizations_path, class: "button success" %>
  </div>
</div>