config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/patients'

  get 'static_pages/doctors'

  get 'static_pages/microbiologists'

  get 'static_pages/accounting'

  devise_for :labs
  devise_for :secretaries
  resources :bills
  resources :illness_details
  resources :hospitalizations
  resources :visits
  resources :blood_chemistry_tests
  resources :blood_tests
  resources :microbiologists
  resources :nurses
  resources :doctors
  devise_for :admins
  resources :patients
  devise_for :users

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :doctor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :patient
  belongs_to :visit
  belongs_to :hospitalization
end

app/models/blood_chemistry_test.rb
class BloodChemistryTest < ActiveRecord::Base
  belongs_to :patient
  belongs_to :microbiologist
end

app/models/blood_test.rb
class BloodTest < ActiveRecord::Base
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :admin
end

app/models/hospitalization.rb
class Hospitalization < ActiveRecord::Base
  belongs_to :doctor
end

app/models/illness_detail.rb
class IllnessDetail < ActiveRecord::Base
  belongs_to :patient
  belongs_to :hospitalization
  belongs_to :visit
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :microbiologist
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/microbiologist.rb
class Microbiologist < ActiveRecord::Base
	belongs_to :lab
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/secretary.rb
class Secretary < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :patient
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :doctor
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_secretary!

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    acumHosp = 0
    acumHemogram = 0
    acumChem = 0
    acumVisit = 0
    honorarioDoctor = 0
    @bill = Bill.new(bill_params)
    @hospitalizations = Hospitalization.all
    @doctors = Doctor.all
    @blood_tests = BloodTest.all
    @blood_chemistry_tests = BloodChemistryTest.all
    @hospitalizations.each do |hospital|
      if hospital.id == @bill.hospitalization_id
        if hospital.payed

        else
          acumHosp += hospital.cost
          hospital.payed = true
        end
      end
      @doctors.each do |doctor|
        if hospital.id == @bill.hospitalization_id && hospital.doctor_id == doctor.id 
          honorarioDoctor = doctor.cost
        end
      end
    end
    @blood_tests.each do |bt|
      if bt.patient_id == @bill.patient_id
        if bt.payed

        else
          acumHemogram += bt.examination_cost
          bt.payed = true
        end
        acumHemogram += bt.examination_cost
      end
    end
    @blood_chemistry_tests.each do |bc|
      if bc.patient_id == @bill.patient_id
        if bc.payed

        else
          acumChem += bc.examination_cost
          bc.payed = true
        end
        
      end
    end
   # @bill.hemogramCost = 0
   # @bill.biochemistryCost = 0
   # @bill.doctorsPayment = 0
   # @bill.hospitalizationCost = 0
   # @bill.total = 0

    @bill.hemogramCost = acumHemogram
    @bill.biochemistryCost = acumChem
    @bill.doctorsPayment = honorarioDoctor
    @bill.hospitalizationCost = acumHosp
    @bill.total = acumHosp+acumChem+acumHemogram+honorarioDoctor
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:patient_id, :billDate, :hospitalizationCost, :hemogramCost, :doctorsPayment, :biochemistryCost, :visit_id, :hospitalization_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/blood_tests_helper.rb
module BloodTestsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/nurses_helper.rb
module NursesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-6 large-centered columns">
      <div class="field">
        <%= f.label :patient_id %><br>
        <%= f.collection_select :patient_id, Patient.all, :id, :email %>
      </div>
      <div class="field">
        <%= f.label :billDate %><br>
        <%= f.date_select :billDate %>
      </div>

      <div class="field">
        <%= f.label :hospitalization_id %><br>
        <%= f.collection_select :hospitalization_id, Hospitalization.all, :id, :id %>
      </div>
    </div>
</div>

<div class="row">
  <div class="twelve columns text-center"><br />
    <div class="actions">
      <%= link_to 'Back', bills_path, class:"button round secondary" %> <%= f.submit "Submit", class:"button round success" %>
    </div>
  </div>
</div>
<% end %>

app/views/bills/edit.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Editing Bill</h1>
  </div>
</div>
<%= render 'form' %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>
<%if secretary_signed_in?%>

<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>Bills Database </h1>
  </div>
</div>

<div class="row">
  <div class="small-12 small-centered columns">

    <table>
      <thead>
        <tr>
          <th>Patient</th>
          <th>Billing Date</th>
          <th>Hospitalization Cost</th>
          <th>Blood Test Cost</th>
          <th>Doctors Payment</th>
          <th>Blood Chemistry Test Cost</th>
          <th>Total</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @bills.each do |bill| %>
          <tr>
            <td><%= bill.patient.name %> <%= bill.patient.lastname %></td>
            <td><%= bill.billDate %></td>
            <td><%= bill.hospitalizationCost %></td>
            <td><%= bill.hemogramCost %></td>
            <td><%= bill.doctorsPayment %></td>
            <td><%= bill.biochemistryCost %></td>
            <td><%= bill.total %></td>
            <td><%= link_to 'Edit', edit_bill_path(bill), class:"button round tiny secondary" %></td>
            <td><%= link_to 'Delete', bill, method: :delete, data: { confirm: 'Are you sure?' }, class:"button round tiny alert" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="twelve columns text-center"><br />
    <%= link_to 'New Bill', new_bill_path, class:"button round success" %>
  </div>
</div>
<%else%>
  You must be logged in as a secretary.
<%end%>

app/views/bills/new.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>New Bill</h1>
  </div>
</div>

<%= render 'form' %>

app/views/bills/show.html.erb
<div class="row">
  <div class="twelve columns text-center"><br />
    <h1>The Bill Has Been Sent To The Patient!</h1>
    <p> Please continue! </p>
    <%= link_to 'Continue', bills_path, class: "button success" %>
  </div>
</div>