config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/patients'

  get 'static_pages/doctors'

  get 'static_pages/microbiologists'

  get 'static_pages/accounting'

  devise_for :labs
  devise_for :secretaries
  resources :bills
  resources :illness_details
  resources :hospitalizations
  resources :visits
  resources :blood_chemistry_tests
  resources :blood_tests
  resources :microbiologists
  resources :nurses
  resources :doctors
  devise_for :admins
  resources :patients
  devise_for :users

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :doctor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :patient
  belongs_to :visit
  belongs_to :hospitalization
end

app/models/blood_test.rb
class BloodTest < ActiveRecord::Base
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :admin
end

app/models/hospitalization.rb
class Hospitalization < ActiveRecord::Base
  belongs_to :doctor
end

app/models/illness_detail.rb
class IllnessDetail < ActiveRecord::Base
  belongs_to :patient
  belongs_to :hospitalization
  belongs_to :visit
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :microbiologist
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/microbiologist.rb
class Microbiologist < ActiveRecord::Base
	belongs_to :lab
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/secretary.rb
class Secretary < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :patient
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :doctor
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/blood_tests_helper.rb
module BloodTestsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/nurses_helper.rb
module NursesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><a href="">Peter John Private Hospital</a></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <% if user_signed_in? %>
            <li>
              <a href="<%= static_pages_home_path %>">Home</a>
            </li>
              <li>
                <a href="<%= patients_path %>">My Profile</a>
              </li>
              <li class="active"><a href="<%= destroy_user_session_path %>">Log Out</a></li>
            <% else %>
              <% if admin_signed_in? %>
              <li>
                <a href="<%= static_pages_home_path %>">Home</a>
              </li>
                <li>
                  <a href="<%= doctors_path %>">My Profile</a>
                </li>
                <li>
                  <a href="<%= patients_path %>">Patients</a>
                </li>
                <li>
                  <a href="<%= visits_path %>">Appointments</a>
                </li>
                <li>
                  <a href="<%= hospitalizations_path %>">Hospitalizations</a>
                </li>
                <li>
                  <a href="<%= illness_details_path %>">Illness Details</a>
                </li>
                <li class="active"><a href="<%= destroy_admin_session_path %>">Log Out</a></li>
              <% else %>
                <% if lab_signed_in? %>
                  <li>
                    <a href="<%= microbiologists_path %>">My Profile</a>
                  </li>
                  <li>
                    <a href="<%= blood_tests_path %>">Complete Blood Tests</a>
                  </li>
                  <li>
                    <a href="<%= blood_chemistry_tests_path %>">Blood Chemistry Tests</a>
                  </li>
                  <li class="active"><a href="<%= destroy_lab_session_path %>">Log Out</a></li>
                <% else %>
                  <% if secretary_signed_in? %>
                    <li>
                      <a href="<%= bills_path %>">Bills</a>
                    </li>
                    <li class="active"><a href="<%= destroy_secretary_session_path %>">Log Out</a></li>
                  <% else %>
                  <li>
                    <a href="<%= static_pages_home_path %>">Home</a>
                  </li>
                  <li>
                    <a href="<%= new_user_session_path %>">Patients</a>
                  </li>
                  <li>
                    <a href="<%= new_admin_session_path %>">Doctors</a>
                  </li>
                  <li>
                    <a href="<%= new_lab_session_path %>">Laboratory</a>
                  </li>
                  <li>
                    <a href="<%= new_secretary_session_path %>">Accounting</a>
                  </li>

                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <!-- Left Nav Section -->
        </section>
      </nav>
    <%= yield %>

  </body>
</html>